=== kevstermcgee/RedEngine/schemas/trace.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Red Engine 2 match trace",
  "description": "A `*.trace.json` written by `--record`. Generated by `red_engine2 schema` from src/content/; do not edit.",
  "type": "object",
  "properties": {
    "trace_version": {
      "type": [
        "integer",
        "null"
      ],
      "format": "uint32",
      "minimum": 0
    },
    "engine": {
      "type": [
        "string",
        "null"
      ]
    },
    "tick_rate": {
      "type": [
        "integer",
        "null"
      ],
      "format": "uint32",
      "minimum": 0
    },
    "scene": {
      "type": [
        "string",
        "null"
      ]
    },
    "map_hash": {
      "type": [
        "integer",
        "null"
      ],
      "format": "uint64",
      "minimum": 0
    },
    "seed": {
      "type": [
        "string",
        "null"
      ]
    },
    "spawn_group": {
      "type": [
        "string",
        "null"
      ]
    },
    "platform": {
      "type": [
        "string",
        "null"
      ]
    },
    "checkpoint_every": {
      "type": [
        "integer",
        "null"
      ],
      "format": "uint32",
      "minimum": 0
    },
    "dump_every": {
      "type": [
        "integer",
        "null"
      ],
      "format": "uint32",
      "minimum": 0
    },
    "entries": {
      "type": [
        "array",
        "null"
      ],
      "items": true
    },
    "checkpoints": {
      "type": [
        "array",
        "null"
      ],
      "items": true
    },
    "events": {
      "type": [
        "array",
        "null"
      ],
      "items": true
    },
    "dumps": {
      "type": [
        "array",
        "null"
      ],
      "items": true
    },
    "final_tick": {
      "type": [
        "integer",
        "null"
      ],
      "format": "uint64",
      "minimum": 0
    }
  },
  "additionalProperties": false,
  "patternProperties": {
    "^(x-|x_|_)|^notes$|^\\$comment$": {}
  },
  "$id": "https://github.com/kevstermcgee/RedEngine/schemas/trace.schema.json"
}

=== kevstermcgee/RedEngine/tests/fixtures/coin_run.trace.json
{"trace_version":2,"engine":"0.1.0","tick_rate":60,"scene":"recipes/coin_run.json","map_hash":2793795152,"seed":"0","spawn_group":"solo","platform":"windows/x86_64","checkpoint_every":6,"dump_every":60,"final_tick":404,"entries":[["j",0,0,0,[3238002688,0,0,0,1070141403,0,0,0]],["i",0,0,1,1,0,0,1061752795,0],["i",1,0,2,1,0,0,1061752794,0],["i",2,0,3,1,0,0,1061752793,0],["i",3,0,4,1,0,0,1061752793,0],["i",4,0,5,1,0,0,1061752792,0],["i",5,0,6,1,0,0,1061752792,0],["i",6,0,7,1,0,0,1061752791,0],["i",7,0,8,1,0,0,1061752790,0],["i",8,0,9,1,0,0,1061752790,0],["i",9,0,10,1,0,0,1061752789,0],["i",10,0,11,1,0,0,1061752788,0],["i",11,0,12,1,0,0,1061752787,0],["i",12,0,13,1,0,0,1061752787,0],["i",13,0,14,1,0,0,1061752786,0],["i",14,0,15,1,0,0,1061752785,0],["i",15,0,16,1,0,0,1061752785,0],["i",16,0,17,1,0,0,1061752784,0],["i",17,0,18,1,0,0,1061752783,0],["i",18,0,19,1,0,0,1061752782,0],["i",19,0,20,1,0,0,1061752781,0],["i",20,0,21,1,0,0,1061752782,0],["i",21,0,22,1,0,0,1061752781,0],["i",22,0,23,1,0,0,1061752782,0],["i",23,0,24,1,0,0,1061752782,0],["i",24,0,25,1,0,0,1061752780,0],["i",25,0,26,1,0,0,1061752781,0],["i",26,0,27,1,0,0,1061752782,0],["i",27,0,28,1,0,0,1061752781,0],["i",28,0,29,1,0,0,1061752782,0],["i",29,0,30,1,0,0,1061752782,0],["i",30,0,31,1,0,0,1061752781,0],["i",31,0,32,1,0,0,1061752782,0],["i",32,0,33,1,0,0,1061752781,0],["i",33,0,34,1,0,0,1061752783,0],["i",34,0,35,1,0,0,1061752781,0],["i",35,0,36,1,0,0,1061752783,0],["i",36,0,37,1,0,0,1061752781,0],["i",37,0,38,1,0,0,1061752783,0],["i",38,0,39,1,0,0,1061752781,0],["i",39,0,40,1,0,0,1061752783,0],["i",40,0,41,1,0,0,1061752781,0],["i",41,0,42,1,0,0,1061752783,0],["i",42,0,43,1,0,0,1061752781,0],["i",43,0,44,1,0,0,1061752783,0],["i",44,0,45,1,0,0,1061752781,0],["i",45,0,46,1,0,0,1061752783,0],["i",46,0,47,1,0,0,1061752781,0],["i",47,0,48,1,0,0,1061752783,0],["i",48,0,49,1,0,0,1061752781,0],["i",49,0,50,1,0,0,1061752783,0],["i",50,0,51,1,0,0,1061752781,0],["i",51,0,52,1,0,0,1061752784,0],["i",52,0,53,1,0,0,1061752781,0],["i",53,0,54,1,0,0,1061752784,0],["i",54,0,55,1,0,0,1061752782,0],["i",55,0,56,1,0,0,1061752780,0],["i",56,0,57,1,0,0,1061752781,0],["i",57,0,58,1,0,0,1061752783,0],["i",58,0,59,1,0,0,1061752780,0],["i",59,0,60,1,0,0,1061752782,0],["i",60,0,61,1,0,0,1061752778,0],["i",61,0,62,1,0,0,1061752780,0],["i",62,0,63,1,0,0,1061752783,0],["i",63,0,64,1,0,0,1061752779,0],["i",64,0,65,1,0,0,1061752781,0],["i",65,0,66,1,0,0,1061752784,0],["i",66,0,67,1,0,0,1061752779,0],["i",67,0,68,1,0,0,1061752782,0],["i",68,0,69,1,0,0,1061752776,0],["i",69,0,70,1,0,0,1061752780,0],["i",70,0,71,1,0,0,1061752784,0],["i",71,0,72,1,0,0,1061752776,0],["i",72,0,73,1,0,0,1061752781,0],["i",73,0,74,1,0,0,1061752787,0],["i",74,0,75,1,0,0,1061752776,0],["i",75,0,76,1,0,0,1075485975,0],["i",76,0,77,1,0,0,1075485975,0],["i",77,0,78,1,0,0,1075485975,0],["i",78,0,79,1,0,0,1075485975,0],["i",79,0,80,1,0,0,1075485975,0],["i",80,0,81,1,0,0,1075485975,0],["i",81,0,82,1,0,0,1075485975,0],["i",82,0,83,1,0,0,1075485975,0],["i",83,0,84,1,0,0,1075485975,0],["i",84,0,85,1,0,0,1075485975,0],["i",85,0,86,1,0,0,1075485975,0],["i",86,0,87,1,0,0,1075485975,0],["i",87,0,88,1,0,0,1075485975,0],["i",88,0,89,1,0,0,1075485975,0],["i",89,0,90,1,0,0,1075485976,0],["i",90,0,91,1,0,0,1075485976,0],["i",91,0,92,1,0,0,1075485976,0],["i",92,0,93,1,0,0,1075485976,0],["i",93,0,94,1,0,0,1075485976,0],["i",94,0,95,1,0,0,1075485976,0],["i",95,0,96,1,0,0,1075485976,0],["i",96,0,97,1,0,0,1075485976,0],["i",97,0,98,1,0,0,1075485976,0],["i",98,0,99,1,0,0,1075485976,0],["i",99,0,100,1,0,0,1075485976,0],["i",100,0,101,1,0,0,1075485976,0],["i",101,0,102,1,0,0,1075485976,0],["i",102,0,103,1,0,0,1075485976,0],["i",103,0,104,1,0,0,1075485976,0],["i",104,0,105,1,0,0,1075485976,0],["i",105,0,106,1,0,0,1075485977,0],["i",106,0,107,1,0,0,1075485977,0],["i",107,0,108,1,0,0,1075485977,0],["i",108,0,109,1,0,0,1075485977,0],["i",109,0,110,1,0,0,1075485977,0],["i",110,0,111,1,0,0,1075485977,0],["i",111,0,112,1,0,0,1075485977,0],["i",112,0,113,1,0,0,1075485977,0],["i",113,0,114,1,0,0,1075485977,0],["i",114,0,115,1,0,0,1075485977,0],["i",115,0,116,1,0,0,1075485977,0],["i",116,0,117,1,0,0,1075485977,0],["i",117,0,118,1,0,0,1075485977,0],["i",118,0,119,1,0,0,1075485977,0],["i",119,0,120,1,0,0,1075485977,0],["i",120,0,121,1,0,0,1075485977,0],["i",121,0,122,1,0,0,1075485977,0],["i",122,0,123,1,0,0,1075485977,0],["i",123,0,124,1,0,0,1075485977,0],["i",124,0,125,1,0,0,1075485977,0],["i",125,0,126,1,0,0,1075485977,0],["i",126,0,127,1,0,0,1075485977,0],["i",127,0,128,1,0,0,1075485977,0],["i",128,0,129,1,0,0,1075485977,0],["i",129,0,130,1,0,0,1075485977,0],["i",130,0,131,1,0,0,1075485977,0],["i",131,0,132,1,0,0,1075485977,0],["i",132,0,133,1,0,0,1075485977,0],["i",133,0,134,1,0,0,1075485977,0],["i",134,0,135,1,0,0,1075485976,0],["i",135,0,136,1,0,0,1075485977,0],["i",136,0,137,1,0,0,1075485976,0],["i",137,0,138,1,0,0,1075485977,0],["i",138,0,139,1,0,0,1075485976,0],["i",139,0,140,1,0,0,1075485976,0],["i",140,0,141,1,0,0,1075485976,0],["i",141,0,142,1,0,0,1075485976,0],["i",142,0,143,1,0,0,1075485976,0],["i",143,0,144,1,0,0,1075485976,0],["i",144,0,145,1,0,0,1075485976,0],["i",145,0,146,1,0,0,1075485976,0],["i",146,0,147,1,0,0,1075485976,0],["i",147,0,148,1,0,0,1075485976,0],["i",148,0,149,1,0,0,1075485976,0],["i",149,0,150,1,0,0,1075485976,0],["i",150,0,151,1,0,0,1075485976,0],["i",151,0,152,1,0,0,1075485976,0],["i",152,0,153,1,0,0,1075485976,0],["i",153,0,154,1,0,0,1075485976,0],["i",154,0,155,1,0,0,1075485976,0],["i",155,0,156,1,0,0,1075485976,0],["i",156,0,157,1,0,0,1075485976,0],["i",157,0,158,1,0,0,1075485976,0],["i",158,0,159,1,0,0,1075485976,0],["i",159,0,160,1,0,0,1075485976,0],["i",160,0,161,1,0,0,1075485976,0],["i",161,0,162,1,0,0,1075485976,0],["i",162,0,163,1,0,0,1075485976,0],["i",163,0,164,1,0,0,1075485976,0],["i",164,0,165,1,0,0,1075485976,0],["i",165,0,166,1,0,0,1075485976,0],["i",166,0,167,1,0,0,1075485976,0],["i",167,0,168,1,0,0,1075485976,0],["i",168,0,169,1,0,0,1075485976,0],["i",169,0,170,1,0,0,1075485976,0],["i",170,0,171,1,0,0,1075485976,0],["i",171,0,172,1,0,0,1075485976,0],["i",172,0,173,1,0,0,1075485975,0],["i",173,0,174,1,0,0,1075485975,0],["i",174,0,175,1,0,0,1075485975,0],["i",175,0,176,1,0,0,1075485975,0],["i",176,0,177,1,0,0,1075485975,0],["i",177,0,178,1,0,0,1075485975,0],["i",178,0,179,1,0,0,1075485975,0],["i",179,0,180,1,0,0,1075485975,0],["i",180,0,181,1,0,0,1075485975,0],["i",181,0,182,1,0,0,1075485975,0],["i",182,0,183,1,0,0,1075485975,0],["i",183,0,184,1,0,0,1075485975,0],["i",184,0,185,1,0,0,1075485974,0],["i",185,0,186,1,0,0,1075485974,0],["i",186,0,187,1,0,0,1075485974,0],["i",187,0,188,1,0,0,1075485974,0],["i",188,0,189,1,0,0,1075485974,0],["i",189,0,190,1,0,0,1075485974,0],["i",190,0,191,1,0,0,1075485974,0],["i",191,0,192,1,0,0,1075485974,0],["i",192,0,193,1,0,0,1075485974,0],["i",193,0,194,1,0,0,1075485974,0],["i",194,0,195,1,0,0,1075485974,0],["i",195,0,196,1,0,0,1075485974,0],["i",196,0,197,1,0,0,1075485974,0],["i",197,0,198,1,0,0,1075485974,0],["i",198,0,199,1,0,0,1075485974,0],["i",199,0,200,1,0,0,1075485974,0],["i",200,0,201,1,0,0,1075485974,0],["i",201,0,202,1,0,0,1075485975,0],["i",202,0,203,1,0,0,1075485974,0],["i",203,0,204,1,0,0,1075485975,0],["i",204,0,205,1,0,0,1075485974,0],["i",205,0,206,1,0,0,1075485975,0],["i",206,0,207,1,0,0,1075485974,0],["i",207,0,208,1,0,0,1075485975,0],["i",208,0,209,1,0,0,1075485974,0],["i",209,0,210,1,0,0,1075485975,0],["i",210,0,211,1,0,0,1075485974,0],["i",211,0,212,1,0,0,1075485975,0],["i",212,0,213,1,0,0,1075485974,0],["i",213,0,214,1,0,0,1075485975,0],["i",214,0,215,1,0,0,1075485974,0],["i",215,0,216,1,0,0,1075485975,0],["i",216,0,217,1,0,0,1075485974,0],["i",217,0,218,1,0,0,1062271546,0],["i",218,0,219,1,0,0,1062271547,0],["i",219,0,220,1,0,0,1062271547,0],["i",220,0,221,1,0,0,1062271546,0],["i",221,0,222,1,0,0,1062271545,0],["i",222,0,223,1,0,0,1062271545,0],["i",223,0,224,1,0,0,1062271546,0],["i",224,0,225,1,0,0,1062271545,0],["i",225,0,226,1,0,0,1062271544,0],["i",226,0,227,1,0,0,1062271545,0],["i",227,0,228,1,0,0,1062271545,0],["i",228,0,229,1,0,0,1062271545,0],["i",229,0,230,1,0,0,1062271544,0],["i",230,0,231,1,0,0,1062271544,0],["i",231,0,232,1,0,0,1062271544,0],["i",232,0,233,1,0,0,1062271544,0],["i",233,0,234,1,0,0,1062271543,0],["i",234,0,235,1,0,0,1062271543,0],["i",235,0,236,1,0,0,1062271543,0],["i",236,0,237,1,0,0,1062271543,0],["i",237,0,238,1,0,0,1062271542,0],["i",238,0,239,1,0,0,1062271542,0],["i",239,0,240,1,0,0,1062271542,0],["i",240,0,241,1,0,0,1062271542,0],["i",241,0,242,1,0,0,1062271542,0],["i",242,0,243,1,0,0,1062271542,0],["i",243,0,244,1,0,0,1062271541,0],["i",244,0,245,1,0,0,1062271542,0],["i",245,0,246,1,0,0,1062271542,0],["i",246,0,247,1,0,0,1062271542,0],["i",247,0,248,1,0,0,1062271542,0],["i",248,0,249,1,0,0,1062271542,0],["i",249,0,250,1,0,0,1062271542,0],["i",250,0,251,1,0,0,1062271542,0],["i",251,0,252,1,0,0,1062271542,0],["i",252,0,253,1,0,0,1062271542,0],["i",253,0,254,1,0,0,1062271542,0],["i",254,0,255,1,0,0,1062271542,0],["i",255,0,256,1,0,0,1062271542,0],["i",256,0,257,1,0,0,1062271542,0],["i",257,0,258,1,0,0,1062271542,0],["i",258,0,259,1,0,0,1062271542,0],["i",259,0,260,1,0,0,1062271542,0],["i",260,0,261,1,0,0,1062271542,0],["i",261,0,262,1,0,0,1062271542,0],["i",262,0,263,1,0,0,1062271542,0],["i",263,0,264,1,0,0,1062271542,0],["i",264,0,265,1,0,0,1062271542,0],["i",265,0,266,1,0,0,1062271543,0],["i",266,0,267,1,0,0,1062271543,0],["i",267,0,268,1,0,0,1062271542,0],["i",268,0,269,1,0,0,1062271542,0],["i",269,0,270,1,0,0,1062271543,0],["i",270,0,271,1,0,0,1062271543,0],["i",271,0,272,1,0,0,1062271542,0],["i",272,0,273,1,0,0,1062271542,0],["i",273,0,274,1,0,0,1062271542,0],["i",274,0,275,1,0,0,1062271542,0],["i",275,0,276,1,0,0,1062271541,0],["i",276,0,277,1,0,0,1062271541,0],["i",277,0,278,1,0,0,1062271541,0],["i",278,0,279,1,0,0,1062271541,0],["i",279,0,280,1,0,0,1062271540,0],["i",280,0,281,1,0,0,1062271539,0],["i",281,0,282,1,0,0,1062271539,0],["i",282,0,283,1,0,0,1062271539,0],["i",283,0,284,1,0,0,1062271538,0],
